CREATE DATABASE mxsms;
USE mxsms;
CREATE TABLE `log` (
    `id` INT(10) NOT NULL AUTO_INCREMENT,
    `mx` VARCHAR(128) NULL DEFAULT NULL,
    `calling` VARCHAR(12) NULL DEFAULT NULL,
    `called` VARCHAR(12) NULL DEFAULT NULL,
    `inbound` BOOLEAN DEFAULT 0,
    `text` VARCHAR(256) NULL DEFAULT NULL,
    `pid` VARCHAR(128) NULL DEFAULT NULL,
    `delivered` INT NULL DEFAULT NULL,
    `type` VARCHAR(12) NULL DEFAULT NULL,
    PRIMARY KEY (`id`)
);